"use client";

import { ImageDown } from "lucide-react";
import { useMemo, useState } from "react";
import type { Cell, ChartSpec, ChartType } from "./types";

type Props = {
  spec: ChartSpec;
  columns: string[];
  rows: Cell[][];
  pro?: boolean;
};

type Point = { label: string; value: number; xValue: number | null };

const MAX_POINTS = 30;
const MAX_SLICES = 8;

function toNumber(value: Cell): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value === "string") {
    // Postgres returns numeric/bigint as strings to preserve precision.
    const n = Number(value.replace(/,/g, ""));
    return value.trim() !== "" && Number.isFinite(n) ? n : null;
  }
  return null;
}

function toLabel(value: Cell): string {
  if (value === null) return "—";
  if (typeof value === "string") {
    const iso = /^(\d{4}-\d{2}-\d{2})T/.exec(value);
    return iso ? iso[1] : value;
  }
  return String(value);
}

function formatValue(n: number): string {
  const abs = Math.abs(n);
  if (abs >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
  if (abs >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (abs >= 10_000) return `${(n / 1_000).toFixed(1)}K`;
  return Number.isInteger(n) ? n.toLocaleString() : n.toFixed(2);
}

/**
 * Grayscale ramp for categorical marks. A monochrome palette has to earn its
 * separation from lightness alone, so slices step from near-black to light gray
 * with a white divider between them.
 */
const SERIES = [
  "var(--color-s1)",
  "var(--color-s2)",
  "var(--color-s3)",
  "var(--color-s4)",
  "var(--color-s5)",
  "var(--color-s6)",
  "var(--color-s7)",
  "var(--color-s8)",
];

/**
 * Categorical hues in fixed order, never cycled — a slice keeps its colour
 * regardless of how many others are present. The order is validated for
 * colour-vision deficiency, and the legend carries text labels and values so
 * identity is never colour alone.
 */
function shade(index: number): string {
  return SERIES[index % SERIES.length];
}

const LABELS: Record<Exclude<ChartType, "none">, string> = {
  bar: "Bar",
  line: "Line",
  area: "Area",
  pie: "Pie",
  scatter: "Scatter",
};

/**
 * Hand-rolled SVG rather than a charting library: the visual language here is
 * one weight of black on a neutral scale, which every library fights you on.
 */
function themeColor(name: string, fallback: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || fallback;
}

function fitLabel(context: CanvasRenderingContext2D, label: string, maxWidth: number): string {
  if (context.measureText(label).width <= maxWidth) return label;
  let shortened = label;
  while (shortened.length > 1 && context.measureText(`${shortened}…`).width > maxWidth) {
    shortened = shortened.slice(0, -1);
  }
  return `${shortened}…`;
}

async function downloadChartAsPng(
  points: Point[],
  spec: ChartSpec,
  type: Exclude<ChartType, "none">,
) {
  const width = 1200;
  const height = 675;
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext("2d");
  if (!context) throw new Error("Canvas is not supported by this browser.");

  const background = themeColor("--color-panel", "#ffffff");
  const foreground = themeColor("--color-fg", "#000000");
  const muted = themeColor("--color-muted", "#666666");
  const accent = themeColor("--color-accent", "#2a78d6");
  const surface = themeColor("--color-surface-hover", "#f2f2f2");
  const series = Array.from({ length: 8 }, (_, index) =>
    themeColor(`--color-s${index + 1}`, accent),
  );

  context.fillStyle = background;
  context.fillRect(0, 0, width, height);
  context.fillStyle = foreground;
  context.font = "600 30px system-ui, sans-serif";
  context.fillText(`${spec.valueColumn} by ${spec.labelColumn}`, 64, 62);
  context.fillStyle = muted;
  context.font = "18px system-ui, sans-serif";
  context.fillText(`${LABELS[type]} chart · generated by Dashu`, 64, 94);

  const left = 80;
  const top = 135;
  const plotWidth = width - 160;
  const plotHeight = height - 215;

  if (type === "bar") {
    const shown = points.slice(0, 12);
    const max = Math.max(...shown.map((point) => point.value), 0) || 1;
    const rowHeight = plotHeight / shown.length;
    const labelWidth = 230;
    shown.forEach((point, index) => {
      const y = top + index * rowHeight + rowHeight / 2;
      context.font = "17px system-ui, sans-serif";
      context.fillStyle = muted;
      context.textAlign = "right";
      context.fillText(fitLabel(context, point.label, labelWidth - 20), left + labelWidth, y + 6);
      context.fillStyle = surface;
      context.fillRect(left + labelWidth + 20, y - 9, plotWidth - labelWidth - 120, 18);
      context.fillStyle = accent;
      context.fillRect(
        left + labelWidth + 20,
        y - 9,
        Math.max(2, (point.value / max) * (plotWidth - labelWidth - 120)),
        18,
      );
      context.fillStyle = foreground;
      context.textAlign = "right";
      context.fillText(formatValue(point.value), left + plotWidth, y + 6);
    });
  } else if (type === "pie") {
    const sorted = [...points].sort((a, b) => b.value - a.value);
    const slices = sorted.length > MAX_SLICES
      ? [
          ...sorted.slice(0, MAX_SLICES - 1),
          {
            label: `Other (${sorted.length - MAX_SLICES + 1})`,
            value: sorted.slice(MAX_SLICES - 1).reduce((sum, point) => sum + point.value, 0),
            xValue: null,
          },
        ]
      : sorted;
    const total = slices.reduce((sum, point) => sum + point.value, 0);
    let angle = -Math.PI / 2;
    const centerX = 350;
    const centerY = top + plotHeight / 2;
    const radius = 190;
    slices.forEach((slice, index) => {
      const next = angle + (slice.value / total) * Math.PI * 2;
      context.beginPath();
      context.moveTo(centerX, centerY);
      context.arc(centerX, centerY, radius, angle, next);
      context.closePath();
      context.fillStyle = series[index % series.length];
      context.fill();
      angle = next;

      const legendY = top + 30 + index * 52;
      context.fillRect(650, legendY - 15, 22, 22);
      context.fillStyle = foreground;
      context.font = "18px system-ui, sans-serif";
      context.textAlign = "left";
      context.fillText(fitLabel(context, slice.label, 280), 690, legendY + 3);
      context.textAlign = "right";
      context.fillText(`${formatValue(slice.value)} · ${((slice.value / total) * 100).toFixed(1)}%`, 1120, legendY + 3);
    });
  } else {
    const values = points.map((point) => point.value);
    const min = Math.min(...values, 0);
    const max = Math.max(...values, 0);
    const span = max - min || 1;
    const xValues = points.map((point) => point.xValue).filter((value): value is number => value !== null);
    const xMin = xValues.length ? Math.min(...xValues) : 0;
    const xMax = xValues.length ? Math.max(...xValues) : points.length - 1;
    const xSpan = xMax - xMin || 1;
    const coordinates = points.map((point, index) => ({
      x: left + (type === "scatter"
        ? (((point.xValue as number) - xMin) / xSpan) * plotWidth
        : (index / Math.max(points.length - 1, 1)) * plotWidth),
      y: top + plotHeight - ((point.value - min) / span) * plotHeight,
      point,
    }));

    context.strokeStyle = surface;
    context.lineWidth = 2;
    context.beginPath();
    context.moveTo(left, top + plotHeight);
    context.lineTo(left + plotWidth, top + plotHeight);
    context.stroke();

    if (type !== "scatter") {
      context.beginPath();
      coordinates.forEach(({ x, y }, index) => index ? context.lineTo(x, y) : context.moveTo(x, y));
      if (type === "area") {
        context.lineTo(left + plotWidth, top + plotHeight);
        context.lineTo(left, top + plotHeight);
        context.closePath();
        context.globalAlpha = 0.18;
        context.fillStyle = accent;
        context.fill();
        context.globalAlpha = 1;
      }
      context.beginPath();
      coordinates.forEach(({ x, y }, index) => index ? context.lineTo(x, y) : context.moveTo(x, y));
      context.strokeStyle = accent;
      context.lineWidth = 5;
      context.lineJoin = "round";
      context.lineCap = "round";
      context.stroke();
    }

    context.fillStyle = accent;
    coordinates.forEach(({ x, y }) => {
      context.beginPath();
      context.arc(x, y, type === "scatter" ? 7 : 5, 0, Math.PI * 2);
      context.fill();
    });
    context.font = "17px system-ui, sans-serif";
    context.fillStyle = muted;
    context.textAlign = "left";
    context.fillText(points[0].label, left, height - 40);
    context.textAlign = "right";
    context.fillText(points[points.length - 1].label, left + plotWidth, height - 40);
  }

  const blob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (value) => value ? resolve(value) : reject(new Error("The browser could not create the PNG.")),
      "image/png",
    );
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `dashu-chart-${new Date().toISOString().slice(0, 10)}.png`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export default function Chart({ spec, columns, rows, pro = false }: Props) {
  const [override, setOverride] = useState<ChartType | null>(null);
  const [exporting, setExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const points = useMemo<Point[]>(() => {
    const labelIdx = columns.indexOf(spec.labelColumn);
    const valueIdx = columns.indexOf(spec.valueColumn);
    if (labelIdx === -1 || valueIdx === -1) return [];

    return rows
      .map((row) => ({
        label: toLabel(row[labelIdx]),
        value: toNumber(row[valueIdx]),
        xValue: toNumber(row[labelIdx]),
      }))
      .filter((p): p is Point => p.value !== null)
      .slice(0, MAX_POINTS);
  }, [columns, rows, spec.labelColumn, spec.valueColumn]);

  const available = useMemo<Exclude<ChartType, "none">[]>(() => {
    if (points.length < 2) return [];
    const types: Exclude<ChartType, "none">[] = ["bar", "line", "area"];
    // Pie only makes sense for a composition: non-negative parts of one whole.
    if (points.every((p) => p.value >= 0) && points.some((p) => p.value > 0)) {
      types.push("pie");
    }
    if (points.every((p) => p.xValue !== null)) types.push("scatter");
    return types;
  }, [points]);

  if (spec.type === "none" || points.length < 2 || available.length === 0) return null;

  // The model proposes; if its choice doesn't fit the data, fall back to bar.
  const requested = override ?? spec.type;
  const type: Exclude<ChartType, "none"> =
    requested !== "none" && available.includes(requested) ? requested : "bar";

  async function exportPng() {
    if (exporting) return;
    setExporting(true);
    setExportError(null);
    try {
      await downloadChartAsPng(points, spec, type);
    } catch (error) {
      setExportError(error instanceof Error ? error.message : "Could not export this chart.");
    } finally {
      setExporting(false);
    }
  }

  return (
    <figure className="mt-4 rounded-lg border bg-surface px-4 pb-4 pt-3">
      <figcaption className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <span className="text-xs font-medium text-muted">
          {spec.valueColumn} by {spec.labelColumn}
        </span>
        <span className="flex items-center gap-1">
          {pro && (
            <button
              type="button"
              onClick={() => void exportPng()}
              disabled={exporting}
              aria-label="Save chart as PNG"
              title="Save chart as PNG"
              className="rounded-md p-1.5 text-muted transition-colors hover:bg-panel hover:text-fg disabled:opacity-40"
            >
              <ImageDown size={14} aria-hidden="true" />
            </button>
          )}
          {available.length > 1 && (
            <span className="flex items-center gap-0.5 rounded-lg border bg-panel p-0.5">
              {available.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setOverride(t)}
                  aria-pressed={t === type}
                  className={`rounded-md px-2 py-1 text-[11px] font-medium transition-colors ${
                    t === type
                      ? "bg-accent text-white"
                      : "text-muted hover:bg-surface hover:text-fg"
                  }`}
                >
                  {LABELS[t as Exclude<ChartType, "none">]}
                </button>
              ))}
            </span>
          )}
        </span>
      </figcaption>
      {exportError && (
        <p role="alert" className="mb-3 text-xs text-red-600 dark:text-red-400">{exportError}</p>
      )}

      {type === "bar" && <BarChart points={points} />}
      {type === "pie" && <PieChart points={points} />}
      {type === "scatter" && <ScatterChart points={points} spec={spec} />}
      {(type === "line" || type === "area") && (
        <LineChart points={points} filled={type === "area"} />
      )}
    </figure>
  );
}

/* -------------------------------------------------------------------------- */

function BarChart({ points }: { points: Point[] }) {
  const max = Math.max(...points.map((p) => p.value), 0);

  return (
    <div className="flex flex-col gap-2.5">
      {points.map((p, i) => (
        <div key={`${p.label}-${i}`} className="flex items-center gap-3 text-xs">
          <span className="w-28 shrink-0 truncate text-right text-muted" title={p.label}>
            {p.label}
          </span>
          <span className="relative h-2 flex-1 overflow-hidden rounded-full bg-panel">
            <span
              className="absolute inset-y-0 left-0 rounded-full bg-accent"
              style={{ width: `${max > 0 ? Math.max((p.value / max) * 100, 1.5) : 0}%` }}
            />
          </span>
          <span className="w-16 shrink-0 text-right font-mono font-medium tabular-nums">
            {formatValue(p.value)}
          </span>
        </div>
      ))}
    </div>
  );
}

/* -------------------------------------------------------------------------- */

function arcPath(
  cx: number,
  cy: number,
  outer: number,
  inner: number,
  start: number,
  end: number,
): string {
  const large = end - start > Math.PI ? 1 : 0;
  const x0 = cx + outer * Math.cos(start);
  const y0 = cy + outer * Math.sin(start);
  const x1 = cx + outer * Math.cos(end);
  const y1 = cy + outer * Math.sin(end);
  const xi1 = cx + inner * Math.cos(end);
  const yi1 = cy + inner * Math.sin(end);
  const xi0 = cx + inner * Math.cos(start);
  const yi0 = cy + inner * Math.sin(start);
  return [
    `M${x0} ${y0}`,
    `A${outer} ${outer} 0 ${large} 1 ${x1} ${y1}`,
    `L${xi1} ${yi1}`,
    `A${inner} ${inner} 0 ${large} 0 ${xi0} ${yi0}`,
    "Z",
  ].join(" ");
}

function PieChart({ points }: { points: Point[] }) {
  // Too many slices is unreadable; roll the tail into one "Other".
  const sorted = [...points].sort((a, b) => b.value - a.value);
  const slices =
    sorted.length > MAX_SLICES
      ? [
          ...sorted.slice(0, MAX_SLICES - 1),
          {
            label: `Other (${sorted.length - MAX_SLICES + 1})`,
            value: sorted.slice(MAX_SLICES - 1).reduce((n, p) => n + p.value, 0),
            xValue: null,
          },
        ]
      : sorted;

  const total = slices.reduce((n, s) => n + s.value, 0);
  if (total <= 0) return null;

  const size = 168;
  const c = size / 2;
  const outer = 78;
  const inner = 46;

  let angle = -Math.PI / 2; // start at twelve o'clock
  const wedges = slices.map((slice, i) => {
    const sweep = (slice.value / total) * Math.PI * 2;
    const start = angle;
    angle += sweep;
    return { ...slice, start, end: angle, fill: shade(i), sweep };
  });

  return (
    <div className="flex flex-wrap items-center gap-x-6 gap-y-4">
      <svg
        viewBox={`0 0 ${size} ${size}`}
        className="h-44 w-44 shrink-0"
        role="img"
        aria-label="Pie chart"
      >
        {wedges.length === 1 ? (
          <circle
            cx={c}
            cy={c}
            r={(outer + inner) / 2}
            fill="none"
            stroke={wedges[0].fill}
            strokeWidth={outer - inner}
          />
        ) : (
          wedges.map((w, i) => (
            <path
              key={i}
              d={arcPath(c, c, outer, inner, w.start, w.end)}
              fill={w.fill}
              stroke="var(--color-panel)"
              strokeWidth={1.5}
            >
              <title>{`${w.label}: ${formatValue(w.value)} (${((w.value / total) * 100).toFixed(1)}%)`}</title>
            </path>
          ))
        )}
        <text
          x={c}
          y={c - 2}
          textAnchor="middle"
          className="fill-current text-[15px] font-medium"
          style={{ fontVariantNumeric: "tabular-nums" }}
        >
          {formatValue(total)}
        </text>
        <text x={c} y={c + 13} textAnchor="middle" className="fill-current text-[9px] opacity-50">
          total
        </text>
      </svg>

      <ul className="min-w-0 flex-1 space-y-1.5">
        {wedges.map((w, i) => (
          <li key={i} className="flex items-center gap-2 text-xs">
            <span
              className="h-2.5 w-2.5 shrink-0 rounded-sm"
              style={{ background: w.fill }}
            />
            <span className="min-w-0 flex-1 truncate text-muted" title={w.label}>
              {w.label}
            </span>
            <span className="shrink-0 font-mono tabular-nums">{formatValue(w.value)}</span>
            <span className="w-11 shrink-0 text-right tabular-nums text-faint">
              {((w.value / total) * 100).toFixed(1)}%
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

/* -------------------------------------------------------------------------- */

const PLOT = { width: 720, height: 180, padX: 4, padY: 14 };

function LineChart({ points, filled }: { points: Point[]; filled: boolean }) {
  const { width, height, padX, padY } = PLOT;
  const values = points.map((p) => p.value);
  const max = Math.max(...values, 0);
  const min = Math.min(...values, 0);
  const span = max - min || 1;
  const stepX = (width - padX * 2) / (points.length - 1);

  const coords = points.map((p, i) => ({
    x: padX + i * stepX,
    y: height - padY - ((p.value - min) / span) * (height - padY * 2),
    ...p,
  }));

  const line = coords.map((c, i) => `${i === 0 ? "M" : "L"}${c.x} ${c.y}`).join(" ");
  const area = `${line} L${coords[coords.length - 1].x} ${height} L${coords[0].x} ${height} Z`;

  return (
    <>
      <svg
        viewBox={`0 0 ${width} ${height}`}
        className="h-44 w-full overflow-visible"
        preserveAspectRatio="none"
        role="img"
        aria-label={filled ? "Area chart" : "Line chart"}
      >
        <path d={area} fill={filled ? "var(--color-accent)" : "var(--color-accent)"}
          fillOpacity={filled ? 0.16 : 0.06} />
        <path
          d={line}
          fill="none"
          stroke="var(--color-accent)"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
          vectorEffect="non-scaling-stroke"
        />
        {!filled &&
          coords.map((c, i) => (
            <circle key={i} cx={c.x} cy={c.y} r={4} fill="var(--color-accent)" stroke="var(--color-panel)" strokeWidth={1.5}>
              <title>{`${c.label}: ${formatValue(c.value)}`}</title>
            </circle>
          ))}
      </svg>
      <div className="mt-2.5 flex justify-between text-xs text-faint">
        <span>{points[0].label}</span>
        <span className="font-mono tabular-nums">
          {formatValue(min)} – {formatValue(max)}
        </span>
        <span>{points[points.length - 1].label}</span>
      </div>
    </>
  );
}

/* -------------------------------------------------------------------------- */

function ScatterChart({ points, spec }: { points: Point[]; spec: ChartSpec }) {
  const { width, height, padY } = PLOT;
  const padX = 10;

  const xs = points.map((p) => p.xValue as number);
  const ys = points.map((p) => p.value);
  const xMin = Math.min(...xs);
  const xMax = Math.max(...xs);
  const yMin = Math.min(...ys, 0);
  const yMax = Math.max(...ys, 0);
  const xSpan = xMax - xMin || 1;
  const ySpan = yMax - yMin || 1;

  const coords = points.map((p) => ({
    cx: padX + ((p.xValue as number) - xMin) / xSpan * (width - padX * 2),
    cy: height - padY - ((p.value - yMin) / ySpan) * (height - padY * 2),
    ...p,
  }));

  return (
    <>
      <svg
        viewBox={`0 0 ${width} ${height}`}
        className="h-44 w-full overflow-visible"
        preserveAspectRatio="none"
        role="img"
        aria-label="Scatter plot"
      >
        <line
          x1={0}
          y1={height - padY}
          x2={width}
          y2={height - padY}
          stroke="rgb(0 0 0 / 0.15)"
          strokeWidth={1}
          vectorEffect="non-scaling-stroke"
        />
        {coords.map((c, i) => (
          <circle key={i} cx={c.cx} cy={c.cy} r={3} fill="var(--color-accent)">
            <title>{`${spec.labelColumn} ${c.label} · ${spec.valueColumn} ${formatValue(c.value)}`}</title>
          </circle>
        ))}
      </svg>
      <div className="mt-2.5 flex justify-between text-xs text-faint">
        <span className="font-mono tabular-nums">{formatValue(xMin)}</span>
        <span>{spec.labelColumn} →</span>
        <span className="font-mono tabular-nums">{formatValue(xMax)}</span>
      </div>
    </>
  );
}
